import { buildHtml } from './html-builder';
import { CapturedSection } from '../models/export.model';
import { MetricScore } from '../models/metric-score.model';
import { ActionItem } from '../models/action-item.model';

describe('buildHtml', () => {
  const mockSections: CapturedSection[] = [
    {
      id: 'flamegraph',
      title: 'Flamegraph',
      imageDataUrl: 'data:image/png;base64,abc',
      width: 800,
      height: 600,
    },
  ];

  const mockMetrics: MetricScore[] = [
    { name: 'Largest Contentful Paint', shortName: 'LCP', value: 2000, displayValue: '2.0s', unit: 'ms', rating: 'good' },
  ];

  const mockActionItems: ActionItem[] = [
    { id: 'a1', severity: 'critical', title: 'Fix LCP', detail: 'LCP is too slow', metric: 'LCP', fix: 'Optimize images' },
  ];

  it('returns a Blob with html content type', () => {
    const result = buildHtml({
      sections: mockSections,
      metrics: mockMetrics,
      actionItems: mockActionItems,
      fileName: 'trace.json',
      fileSize: 1024,
      analyzedAt: new Date('2026-07-20T12:00:00Z'),
    });

    expect(result).toBeInstanceOf(Blob);
    expect(result.type).toBe('text/html');
  });

  it('includes DOCTYPE and basic HTML structure', async () => {
    const result = buildHtml({
      sections: mockSections,
      metrics: mockMetrics,
      actionItems: [],
      fileName: 'trace.json',
      fileSize: 1024,
      analyzedAt: new Date('2026-07-20T12:00:00Z'),
    });

    const text = await result.text();
    expect(text).toContain('<!DOCTYPE html>');
    expect(text).toContain('<html lang="en">');
    expect(text).toContain('</html>');
  });

  it('includes the file name in the title and header', async () => {
    const result = buildHtml({
      sections: mockSections,
      metrics: mockMetrics,
      actionItems: [],
      fileName: 'my-trace.json',
      fileSize: 1024,
      analyzedAt: new Date('2026-07-20T12:00:00Z'),
    });

    const text = await result.text();
    expect(text).toContain('PerfLens Report');
    expect(text).toContain('my-trace.json');
  });

  it('includes metrics in the report', async () => {
    const result = buildHtml({
      sections: mockSections,
      metrics: mockMetrics,
      actionItems: [],
      fileName: 'trace.json',
      fileSize: 1024,
      analyzedAt: new Date('2026-07-20T12:00:00Z'),
    });

    const text = await result.text();
    expect(text).toContain('LCP');
    expect(text).toContain('2.0s');
  });

  it('includes action items as an HTML table', async () => {
    const result = buildHtml({
      sections: mockSections,
      metrics: mockMetrics,
      actionItems: mockActionItems,
      fileName: 'trace.json',
      fileSize: 1024,
      analyzedAt: new Date('2026-07-20T12:00:00Z'),
    });

    const text = await result.text();
    expect(text).toContain('<table');
    expect(text).toContain('Fix LCP');
    expect(text).toContain('CRITICAL');
  });

  it('embeds section images as base64 img tags', async () => {
    const result = buildHtml({
      sections: mockSections,
      metrics: mockMetrics,
      actionItems: [],
      fileName: 'trace.json',
      fileSize: 1024,
      analyzedAt: new Date('2026-07-20T12:00:00Z'),
    });

    const text = await result.text();
    expect(text).toContain('<img');
    expect(text).toContain('data:image/png;base64,abc');
    expect(text).toContain('Flamegraph');
  });

  it('includes inlined styles', async () => {
    const result = buildHtml({
      sections: mockSections,
      metrics: mockMetrics,
      actionItems: [],
      fileName: 'trace.json',
      fileSize: 1024,
      analyzedAt: new Date('2026-07-20T12:00:00Z'),
    });

    const text = await result.text();
    expect(text).toContain('<style>');
    expect(text).toContain('@media print');
  });

  it('includes a footer', async () => {
    const result = buildHtml({
      sections: [],
      metrics: [],
      actionItems: [],
      fileName: 'trace.json',
      fileSize: 1024,
      analyzedAt: new Date('2026-07-20T12:00:00Z'),
    });

    const text = await result.text();
    expect(text).toContain('Generated by PerfLens');
  });
});
