import { CapturedSection } from '../models/export.model';
import { MetricScore } from '../models/metric-score.model';
import { ActionItem } from '../models/action-item.model';

export interface HtmlBuildInput {
  sections: CapturedSection[];
  metrics: MetricScore[];
  actionItems: ActionItem[];
  fileName: string;
  fileSize: number;
  analyzedAt: Date;
}

export function buildHtml(input: HtmlBuildInput): Blob {
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PerfLens Report — ${escapeHtml(input.fileName)}</title>
  <style>${getStyles()}</style>
</head>
<body>
  <header class="report-header">
    <h1>⚡ PerfLens Report</h1>
    <div class="meta">
      <span>File: ${escapeHtml(input.fileName)}</span>
      <span>Size: ${formatFileSize(input.fileSize)}</span>
      <span>Analyzed: ${input.analyzedAt.toISOString().split('T')[0]}</span>
    </div>
  </header>

  ${renderMetricsSection(input.metrics)}
  ${renderActionItemsSection(input.actionItems)}
  ${renderCapturedSections(input.sections)}

  <footer class="report-footer">
    Generated by PerfLens • ${input.analyzedAt.toISOString().split('T')[0]}
  </footer>
</body>
</html>`;

  return new Blob([html], { type: 'text/html' });
}

function renderMetricsSection(metrics: MetricScore[]): string {
  if (metrics.length === 0) return '';

  const cards = metrics.map(m => `
    <div class="metric-card metric-${escapeHtml(m.rating)}">
      <div class="metric-name">${escapeHtml(m.shortName)}</div>
      <div class="metric-value">${escapeHtml(m.displayValue)}</div>
      <div class="metric-rating">${escapeHtml(m.rating)}</div>
    </div>
  `).join('');

  return `<section class="metrics"><h2>Performance Metrics</h2><div class="metric-grid">${cards}</div></section>`;
}

function renderActionItemsSection(items: ActionItem[]): string {
  if (items.length === 0) return '';

  const rows = items.map(item => `
    <tr>
      <td><span class="severity severity-${escapeHtml(item.severity)}">${escapeHtml(item.severity.toUpperCase())}</span></td>
      <td><span class="metric-tag">${escapeHtml(item.metric)}</span></td>
      <td><strong>${escapeHtml(item.title)}</strong><br><span class="detail">${escapeHtml(item.detail)}</span></td>
      <td class="fix">${escapeHtml(item.fix)}</td>
    </tr>
  `).join('');

  return `
    <section class="action-items">
      <h2>Action Items</h2>
      <table>
        <thead><tr><th>Severity</th><th>Metric</th><th>Issue</th><th>Fix</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </section>`;
}

function renderCapturedSections(sections: CapturedSection[]): string {
  return sections.map(section => `
    <section class="captured-section">
      <h2>${escapeHtml(section.title)}</h2>
      <img src="${escapeHtml(section.imageDataUrl)}" alt="${escapeHtml(section.title)}" style="max-width:100%; height:auto;">
    </section>
  `).join('');
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function formatFileSize(bytes: number): string {
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

function getStyles(): string {
  return `
    :root { --bg: #0d1117; --card-bg: #1a1f2e; --text: #e6edf3; --text-muted: #8b949e; --green: #10b981; --amber: #f59e0b; --red: #ef4444; --blue: #3b82f6; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Helvetica, Arial, sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; padding: 2rem; max-width: 1200px; margin: 0 auto; }
    h1 { color: var(--green); font-size: 1.8rem; margin-bottom: 0.5rem; }
    h2 { color: var(--text); font-size: 1.3rem; margin: 2rem 0 1rem; border-bottom: 1px solid #30363d; padding-bottom: 0.5rem; }
    .report-header { margin-bottom: 2rem; }
    .meta { display: flex; gap: 2rem; color: var(--text-muted); font-size: 0.9rem; }
    .metric-grid { display: flex; gap: 1rem; flex-wrap: wrap; }
    .metric-card { background: var(--card-bg); border-radius: 8px; padding: 1rem; text-align: center; min-width: 120px; flex: 1; border-left: 3px solid var(--text-muted); }
    .metric-good { border-left-color: var(--green); }
    .metric-needs-improvement { border-left-color: var(--amber); }
    .metric-poor { border-left-color: var(--red); }
    .metric-name { font-size: 0.75rem; text-transform: uppercase; color: var(--text-muted); letter-spacing: 0.05em; }
    .metric-value { font-size: 1.5rem; font-weight: bold; margin: 0.25rem 0; }
    .metric-rating { font-size: 0.75rem; color: var(--text-muted); }
    table { width: 100%; border-collapse: collapse; background: var(--card-bg); border-radius: 8px; overflow: hidden; }
    th, td { padding: 0.75rem 1rem; text-align: left; border-bottom: 1px solid #30363d; }
    th { background: #161b22; color: var(--text-muted); font-size: 0.8rem; text-transform: uppercase; }
    .severity { font-size: 0.75rem; font-weight: 600; padding: 2px 8px; border-radius: 4px; }
    .severity-critical { background: rgba(239,68,68,0.2); color: var(--red); }
    .severity-warning { background: rgba(245,158,11,0.2); color: var(--amber); }
    .severity-info { background: rgba(59,130,246,0.2); color: var(--blue); }
    .metric-tag { font-size: 0.75rem; background: #21262d; color: var(--text-muted); padding: 2px 8px; border-radius: 4px; }
    .detail { color: var(--text-muted); font-size: 0.85rem; }
    .fix { color: var(--green); font-size: 0.85rem; }
    .captured-section img { border-radius: 8px; border: 1px solid #30363d; }
    .report-footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #30363d; color: var(--text-muted); font-size: 0.8rem; text-align: center; }

    @media print {
      :root { --bg: #fff; --card-bg: #f6f8fa; --text: #1f2328; --text-muted: #656d76; }
      body { padding: 1rem; }
      .captured-section img { border: 1px solid #d0d7de; }
    }
  `;
}
