import { jsPDF } from 'jspdf';
import { CapturedSection } from '../models/export.model';
import { MetricScore } from '../models/metric-score.model';
import { ActionItem, Severity } from '../models/action-item.model';

const MARGIN = 15; // mm
const PAGE_WIDTH = 297; // A4 landscape
const PAGE_HEIGHT = 210;
const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;

export interface PdfBuildInput {
  sections: CapturedSection[];
  metrics: MetricScore[];
  actionItems: ActionItem[];
  fileName: string;
  fileSize: number;
  analyzedAt: Date;
}

export function buildPdf(input: PdfBuildInput): Blob {
  const doc = new jsPDF({
    orientation: 'landscape',
    unit: 'mm',
    format: 'a4',
  });

  renderCoverPage(doc, input);

  if (input.actionItems.length > 0) {
    doc.addPage();
    renderActionItemsPage(doc, input.actionItems);
  }

  for (const section of input.sections) {
    doc.addPage();
    renderSectionPage(doc, section);
  }

  renderFooters(doc, input.analyzedAt);

  const arrayBuffer = doc.output('arraybuffer');
  return new Blob([arrayBuffer], { type: 'application/pdf' });
}

function renderCoverPage(doc: jsPDF, input: PdfBuildInput): void {
  let y = 40;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(16, 185, 129); // emerald-500
  doc.text('⚡ PerfLens Report', MARGIN, y);
  y += 20;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  doc.setTextColor(60, 60, 60);
  doc.text(`File: ${input.fileName}`, MARGIN, y);
  y += 8;

  const fileSizeStr = input.fileSize < 1024 * 1024
    ? `${(input.fileSize / 1024).toFixed(1)} KB`
    : `${(input.fileSize / (1024 * 1024)).toFixed(1)} MB`;
  doc.text(`Size: ${fileSizeStr}`, MARGIN, y);
  y += 8;

  doc.text(`Analyzed: ${input.analyzedAt.toISOString().split('T')[0]}`, MARGIN, y);
  y += 16;

  if (input.metrics.length > 0) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(16);
    doc.setTextColor(30, 30, 30);
    doc.text('Performance Metrics', MARGIN, y);
    y += 10;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(12);

    for (const metric of input.metrics) {
      const color = ratingColor(metric.rating);
      doc.setTextColor(...color);
      doc.text(`${metric.shortName}: ${metric.displayValue}  (${metric.rating})`, MARGIN + 4, y);
      y += 7;
    }
  }
}

function renderActionItemsPage(doc: jsPDF, items: ActionItem[]): void {
  let y = MARGIN;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(30, 30, 30);
  doc.text('Action Items', MARGIN, y);
  y += 10;

  doc.setFontSize(10);

  for (const item of items) {
    if (y > PAGE_HEIGHT - MARGIN - 20) {
      doc.addPage();
      y = MARGIN;
    }

    const color = severityColor(item.severity);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...color);
    doc.text(`[${item.severity.toUpperCase()}]`, MARGIN, y);

    doc.setFont('helvetica', 'normal');
    doc.setTextColor(30, 30, 30);
    doc.text(`${item.title}`, MARGIN + 25, y);
    y += 5;

    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    const detailLines = doc.splitTextToSize(item.detail, CONTENT_WIDTH - 25);
    doc.text(detailLines, MARGIN + 25, y);
    y += detailLines.length * 4 + 4;
    doc.setFontSize(10);
  }
}

function renderSectionPage(doc: jsPDF, section: CapturedSection): void {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(30, 30, 30);
  doc.text(section.title, MARGIN, MARGIN + 5);

  const imageY = MARGIN + 12;
  const availableHeight = PAGE_HEIGHT - imageY - MARGIN;
  const aspectRatio = section.width / section.height;
  let imgWidth = CONTENT_WIDTH;
  let imgHeight = imgWidth / aspectRatio;

  if (imgHeight > availableHeight) {
    imgHeight = availableHeight;
    imgWidth = imgHeight * aspectRatio;
  }

  doc.addImage(section.imageDataUrl, 'PNG', MARGIN, imageY, imgWidth, imgHeight);
}

function renderFooters(doc: jsPDF, analyzedAt: Date): void {
  const totalPages = doc.getNumberOfPages();
  const dateStr = analyzedAt.toISOString().split('T')[0];

  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by PerfLens • ${dateStr} • Page ${i} of ${totalPages}`,
      PAGE_WIDTH / 2,
      PAGE_HEIGHT - 5,
      { align: 'center' },
    );
  }
}

function severityColor(severity: Severity): [number, number, number] {
  switch (severity) {
    case 'critical': return [220, 38, 38];
    case 'warning': return [217, 119, 6];
    case 'info': return [37, 99, 235];
  }
}

function ratingColor(rating: string): [number, number, number] {
  switch (rating) {
    case 'good': return [22, 163, 74];
    case 'needs-improvement': return [217, 119, 6];
    case 'poor': return [220, 38, 38];
    default: return [60, 60, 60];
  }
}
